### ISSUE TITLE
Sorting by Date

### ISSUE THREAD

**Issue by JayVii** [davorg/perlanet#2]
perlanet somehow does not sort articles of multiple feeds by date/time.
This is especially true for larger numbers of feeds (I got ~99 feeds in my rc)

Is there anything I can do about that within perlanet or can I sort the restulting atom.xml with another tool?

perlanetrc:
```
title: YouTube-Feed
  description: YouTube Subscriptions
  url: http://localhost
  author:
    name: JayVii
  entries: 1000
  entried_per_feed: 0
  page:
    file: youtube.html
    template: template.tt
  feed:
    file: atom.xml
    format: Atom
  feeds:
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UClyj767bcu6WYyN_Il7eaGw
... [98 more feeds]...
```
templatefile:
```
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>[% feed.title %]</title>
    </head>
    <body>
      <h1>[% feed.title | html %]</h1>
  [% FOREACH entry IN feed.entries %]
      <h2><a href="[% entry.link | url | html %]">[% entry.title | html %]</h2></a>
      [% entry.content.body %]
  [% IF entry.author OR entry.issued %]
      <p>Published[% IF entry.author %] by [% entry.author | html; END %]
      [% IF entry.issued %] on [% entry.issued | html; END %]</p>
  [% END %]
  [% END %]
      <hr />
      <address>[% feed.author | html %] / [% feed.modified | html %]</address>
    </body>
  </html>
```
